MVC/Controllers/AdminController.cs
using DataAccess.Concrete;
using DataAccess.Concrete.Context;
using Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ServiceModel.Syndication;
using System.Xml;
using HtmlAgilityPack;

namespace MVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly ExamContext _context;

        AdminDal _adminDal;
        ExamDal _examDal;
        public AdminController(ExamContext context)
        {
            _context = context;
            _adminDal = new AdminDal(context);
            _examDal = new ExamDal(context);
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View(new Admin());
        }

        [HttpPost]

        public ActionResult LogIn(Admin admin)
        {
            if (_adminDal.CanLogin(admin))
            {
               Admin newAdmin=  _adminDal.Get(a=>a.UserName==admin.UserName);
                AddCookie(newAdmin);
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("GirisHata", "Bilgileri kontrol ediniz."); //todo:check
            return View(admin);
        }


        private void AddCookie(Admin admin)
        {

            if ( string.IsNullOrEmpty(Request.Cookies["id"]))
            {
                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddMinutes(40);
               
                Response.Cookies.Append("id",  admin.Id.ToString(), options);
            }
        }

        public ActionResult Show()
        {
            List<Exam> exams = new List<Exam>();
            IEnumerable<Exam> list = _examDal.GetLatestFivePosts();
            foreach (var item in list)
            {
                Exam exam = _examDal.GetPost(item);
                exam.Admin = _adminDal.GetByID(int.Parse(Request.Cookies["id"]));
                exam.AdminId = int.Parse(Request.Cookies["id"]);

                _examDal.Add(exam);
                exams.Add(exam);
            }
            return View(exams);
        }



       



        //public static IEnumerable<FeedItem> GetLatestFivePosts()
        //{
        //    var reader = XmlReader.Create("https://sibeeshpassion.com/feed/");
        //    var feed = SyndicationFeed.Load(reader);
        //    reader.Close();
        //    return (from itm in feed.Items
        //            select new FeedItem
        //            {
        //                Title = itm.Title.Text,
        //                Link = itm.Id
        //            }).ToList().Take(5);
        //}

        //public class FeedItem
        //{
        //    public string Title
        //    {
        //        get;
        //        set;
        //    }
        //    public string Link
        //    {
        //        get;
        //        set;
        //    }
        //}






        // GET: AdminController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Controllers/ExamController.cs
using DataAccess.Concrete;
using DataAccess.Concrete.Context;
using Entities.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Controllers
{
    public class ExamController : Controller
    {

        private readonly ExamContext _context;
        ExamDal _examDal;
        AdminDal _adminDal;
        public ExamController(ExamContext examContext)
        {
            _context = examContext;
            _examDal = new ExamDal(examContext);
            _adminDal = new AdminDal(examContext);

        }

        [HttpGet]
        public ActionResult CreateExam(int id)
        {
            //Exam exam = _examDal.GetByID(id);
            //exam.AdminId =int.Parse(Request.Cookies["id"]);
            //exam.Admin = _adminDal.GetByID(int.Parse(Request.Cookies["id"]));

            Exam exam = _examDal.GetByID(id);
            ExamDto examDto = new ExamDto();
            examDto.Title = exam.Title;
            examDto.Content = exam.Content;

           
            return View(examDto);

        }


        [HttpPost]
        public ActionResult CreateExam(Exam exam)
        {
            if (!string.IsNullOrEmpty(Request.Cookies["id"]))
            {
              
                exam.AdminId = int.Parse(Request.Cookies["id"]);
                exam.IsActive = true;
                
                _examDal.Add(exam);
                return RedirectToAction("Index", "Home");
            }
            else return RedirectToAction("Index", "Home"); //todo: chechk ayrım yap
        }


        // GET: ExamController
        public ActionResult Index()
        {
            return View();
        }

        // GET: ExamController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ExamController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExamController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ExamController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ExamController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ExamController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ExamController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Views/Admin/LogIn.cshtml
@model Entities.Concrete.Admin;

<link href="~/vendor-fontawesome-all-min.css" rel="stylesheet" />

<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet">

<link href="~/sb-admin-2min.css" rel="stylesheet" />




<body class="bg-gradient-primary">

    <div class="container">
      
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5" style="width:700px">
                    <div class="card-body p-0">
                      
                        <div class="row">
                            


                                <div class="col-lg-12">
                                    <div class="p-5">
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">Hoşgeldiniz!</h1>
                                        </div>
                                        <form asp-controller="Admin" method="post" asp-action="LogIn">
                                            <div asp-validation-summary="ModelOnly" class="text-danger">

                                            </div>
                                            <div class="form-group">
                                                <input asp-for="UserName" name="UserName" type="text" class="form-control form-control-user"
                                                       id="exampleInputEmail" aria-describedby="emailHelp"
                                                       placeholder="Kullanıcı adınızı giriniz">
                                                <span asp-validation-for="UserName" class="text-danger"></span>
                                            </div>
                                            <div class="form-group">
                                                <input asp-for="Password" name="Password" type="password" class="form-control form-control-user"
                                                       id="exampleInputPassword" placeholder="Şifrenizi giriniz.">
                                                <span asp-validation-for="Password" class="text-danger"></span>
                                            </div>

                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Giriş Yap
                                            </button>


                                        </form>



                                    </div>
                                </div>
                           
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>


</body>

MVC/Views/Admin/Show.cshtml
@model IEnumerable<Entities.Concrete.Exam>


@section body {



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css">

    <!-- Custom fonts for this template -->

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">


    <link href="~/all.css" rel="stylesheet" />

    <!-- Custom styles for this template -->

    <link href="~/sb-admin-2min.css" rel="stylesheet" />


    <!-- Custom styles for this page -->

    <link href="~/datatable-bootstrap4-min.css" rel="stylesheet" />





    <div class="container-fluid" style="margin-top:20px">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Sınavlar</h6>
            </div>
            <div>
                <h6><a asp-controller="Home" asp-action="Index">Anasayfaya Dön</a></h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

                        <div class="row">
                            <div class="col-sm-12">

                                <table data-toggle="table" data-page-size="20" data-pagination="true" data-page-list="[1,5,20]">
                                    <thead>
                                        <tr>

                                            <th hidden data-sortable="true">
                                                @Html.DisplayNameFor(model => model.Title)
                                            </th>
                                            <th data-sortable="true">
                                                @Html.DisplayNameFor(model => model.CreatedDate)
                                            </th>
                                            <th data-sortable="true">
                                                @Html.DisplayNameFor(model => model.IsActive)
                                            </th>

                                            @*<th>

        </th>*@
                                        </tr>
                                    </thead>
                                    <tbody id="myTable">

                                        @foreach (var item in Model)
                                        {

                                            <tr>

                                                <td>
                                                    @*@Html.DisplayFor(modelItem => item.Title)*@
                                                    @Html.ActionLink(item.Title, "CreateExam","Exam", new { id = item.Id })
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CreatedDate)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.IsActive)
                                                </td>


                                                @*<td>
                                                        @Html.ActionLink("Sil", "Delete", new { id = item.Id })
                                                    </td>*@


                                            </tr>

                                        }

                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>
                </div>
            </div>



        </div>


    </div>

}


@section Scripts{

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>


    <script>
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
}